### ISSUE TITLE
function 'dump' not found or invalid function name

### ISSUE THREAD

**Issue by Coysh** [studioespresso/craft3-dumper#6]
Hi,

Getting an error on this:
![image](https://user-images.githubusercontent.com/5764356/39588178-29be0ea6-4ef3-11e8-84a7-9132a06e5639.png)

```yii\base\ErrorException: call_user_func_array() expects parameter 1 to be a valid callback, function 'dump' not found or invalid function name in /home/vagrant/sites/eauk-org/vendor/larapack/dd/src/helper.php:16
Stack trace:
#0 /home/vagrant/sites/eauk-org/vendor/craftcms/cms/src/web/ErrorHandler.php(84): yii\base\ErrorHandler->handleError(2, 'call_user_func_...', '/home/vagrant/s...', 16)
#1 /home/vagrant/sites/eauk-org/vendor/larapack/dd/src/helper.php(16): craft\web\ErrorHandler->handleError(2, 'call_user_func_...', '/home/vagrant/s...', 16, Array)
#2 /home/vagrant/sites/eauk-org/vendor/studioespresso/craft-dumper/src/web/twig/DumperExtension.php(54): d(Object(craft\elements\Category))
#3 /home/vagrant/sites/eauk-org/storage/runtime/compiled_templates/4d/4da36537b9714c18a9c817a4182454df8c619090f0074923fb6e1471dd238c95.php(105): studioespresso\craftdumper\web\twig\DumperExtension->d(Object(craft\elements\Category))
#4 /home/vagrant/sites/eauk-org/vendor/twig/twig/lib/Twig/Template.php(390): __TwigTemplate_bd1027264720327fe23621a641af4bb31901e9796264bcf93e6bec61818196ec->doDisplay(Array, Array)
#5 /home/vagrant/sites/eauk-org/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#6 /home/vagrant/sites/eauk-org/vendor/twig/twig/lib/Twig/Template.php(367): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#7 /home/vagrant/sites/eauk-org/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#8 /home/vagrant/sites/eauk-org/storage/runtime/compiled_templates/97/97013b147239fafe52524e9224f40fee574a8ab821164e42d56938ef24dce908.php(99): craft\web\twig\Template->display(Array)
#9 /home/vagrant/sites/eauk-org/vendor/twig/twig/lib/Twig/Template.php(390): __TwigTemplate_49dabcfc5bf932096dd63fadc99ed0562f9030e5f1c2993f42953dbe5bffee48->doDisplay(Array, Array)
#10 /home/vagrant/sites/eauk-org/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#11 /home/vagrant/sites/eauk-org/vendor/twig/twig/lib/Twig/Template.php(367): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#12 /home/vagrant/sites/eauk-org/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#13 /home/vagrant/sites/eauk-org/storage/runtime/compiled_templates/3c/3cc894f268bcf36cf700d8bf42bae09d2e91c0cb92cd6a90045d4cfdbcae13ad.php(36): craft\web\twig\Template->display(Array)
#14 /home/vagrant/sites/eauk-org/vendor/twig/twig/lib/Twig/Template.php(189): __TwigTemplate_647b3ff01d031c781e857bdf492d7eb519bce9b70ac681202448fb9154ccdd8e->block_main(Array, Array)
#15 /home/vagrant/sites/eauk-org/storage/runtime/compiled_templates/77/7739038160e454db2850af6064deee01e1065a00ddffc1c97d5331621f3a9741.php(375): Twig_Template->displayBlock('main', Array, Array)
#16 /home/vagrant/sites/eauk-org/vendor/twig/twig/lib/Twig/Template.php(189): __TwigTemplate_76e69c89a139b51dc07ffeb70c371702111b12c85c2dc8dd266c9221a7788ac2->block_body(Array, Array)
#17 /home/vagrant/sites/eauk-org/storage/runtime/compiled_templates/57/572649285e624ca67c08d3100edfa511d627a7eef82484bf9e8c697be298dced.php(122): Twig_Template->displayBlock('body', Array, Array)
#18 /home/vagrant/sites/eauk-org/vendor/twig/twig/lib/Twig/Template.php(390): __TwigTemplate_a3db40d5084156133bcc3012a24868054e45ab836cb153462ea1980a6dea6550->doDisplay(Array, Array)
#19 /home/vagrant/sites/eauk-org/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#20 /home/vagrant/sites/eauk-org/vendor/twig/twig/lib/Twig/Template.php(367): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#21 /home/vagrant/sites/eauk-org/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#22 /home/vagrant/sites/eauk-org/storage/runtime/compiled_templates/77/7739038160e454db2850af6064deee01e1065a00ddffc1c97d5331621f3a9741.php(64): craft\web\twig\Template->display(Array, Array)
#23 /home/vagrant/sites/eauk-org/vendor/twig/twig/lib/Twig/Template.php(390): __TwigTemplate_76e69c89a139b51dc07ffeb70c371702111b12c85c2dc8dd266c9221a7788ac2->doDisplay(Array, Array)
#24 /home/vagrant/sites/eauk-org/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#25 /home/vagrant/sites/eauk-org/vendor/twig/twig/lib/Twig/Template.php(367): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#26 /home/vagrant/sites/eauk-org/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#27 /home/vagrant/sites/eauk-org/storage/runtime/compiled_templates/3c/3cc894f268bcf36cf700d8bf42bae09d2e91c0cb92cd6a90045d4cfdbcae13ad.php(28): craft\web\twig\Template->display(Array, Array)
#28 /home/vagrant/sites/eauk-org/vendor/twig/twig/lib/Twig/Template.php(390): __TwigTemplate_647b3ff01d031c781e857bdf492d7eb519bce9b70ac681202448fb9154ccdd8e->doDisplay(Array, Array)
#29 /home/vagrant/sites/eauk-org/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#30 /home/vagrant/sites/eauk-org/vendor/twig/twig/lib/Twig/Template.php(367): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#31 /home/vagrant/sites/eauk-org/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#32 /home/vagrant/sites/eauk-org/vendor/twig/twig/lib/Twig/Template.php(375): craft\web\twig\Template->display(Array)
#33 /home/vagrant/sites/eauk-org/vendor/twig/twig/lib/Twig/Environment.php(289): Twig_Template->render(Array)
#34 /home/vagrant/sites/eauk-org/vendor/craftcms/cms/src/web/View.php(305): Twig_Environment->render('pages/news-and-...', Array)
#35 /home/vagrant/sites/eauk-org/vendor/craftcms/cms/src/web/View.php(352): craft\web\View->renderTemplate('pages/news-and-...', Array)
#36 /home/vagrant/sites/eauk-org/vendor/craftcms/cms/src/web/Controller.php(128): craft\web\View->renderPageTemplate('pages/news-and-...', Array)
#37 /home/vagrant/sites/eauk-org/vendor/craftcms/cms/src/controllers/TemplatesController.php(78): craft\web\Controller->renderTemplate('pages/news-and-...', Array)
#38 [internal function]: craft\controllers\TemplatesController->actionRender('pages/news-and-...', Array)
#39 /home/vagrant/sites/eauk-org/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#40 /home/vagrant/sites/eauk-org/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#41 /home/vagrant/sites/eauk-org/vendor/craftcms/cms/src/web/Controller.php(76): yii\base\Controller->runAction('render', Array)
#42 /home/vagrant/sites/eauk-org/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('render', Array)
#43 /home/vagrant/sites/eauk-org/vendor/craftcms/cms/src/web/Application.php(274): yii\base\Module->runAction('templates/rende...', Array)
#44 /home/vagrant/sites/eauk-org/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('templates/rende...', Array)
#45 /home/vagrant/sites/eauk-org/vendor/craftcms/cms/src/web/Application.php(263): yii\web\Application->handleRequest(Object(craft\web\Request))
#46 /home/vagrant/sites/eauk-org/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#47 /home/vagrant/sites/eauk-org/public/index.php(17): yii\base\Application->run()
#48 {main}```

**Comment by janhenckens** [comment]
Could you provide a bit more information? (PHP version, craft version, in what type of file you're trying to use d/dd)

Thanks

**Comment by janhenckens** [comment]
No feedback, closing this for now.
